quotation/urls.py
from argparse import Namespace
from django.urls import path, re_path
from quotation import views

app_name = 'quotation'
urlpatterns = [
    path('quotation-list-status/<int:pk>/', views.quotation_list_status, name='quotation_list_status'),
    path('quotation-list-channel/<int:pk>/', views.quotation_list_channel, name='quotation_list_channel'),
    path('search_quotation/', views.search_quotation, name='search_quotation'),
    path('quotation_update/<int:pk>/', views.quotation_update, name='quotation_update'),
    path('quotation_delete/<int:pk>/', views.quotation_delete, name='quotation_delete'),
    path('add_product_to_quotation/<int:pk>/', views.quotation_product_input, name='quotation_product_input'),
    path('quotation_product_delete/<int:pk>/', views.quotation_product_delete, name='quotation_product_delete'),
    path('quotation/<int:pk>/', views.final_quotation, name='final_quotation'),
    path('quotation_pdf/<int:pk>/', views.html_to_pdf_view, name='html_to_pdf_view'),
    path('contract/', views.contract, name='contract'),
    path('contract_view/<int:pk>/', views.contract_view, name='contract_view'),
    path('contract-list-status/<int:pk>/', views.contract_list_status, name='contract_list_status'),
    path('contract-list-channel/<int:pk>/', views.contract_list_channel, name='contract_list_channel'),
    path('search_contract/', views.search_contract, name='search_contract'),
    path('contract_update/<int:pk>/', views.contract_update, name='contract_update'),
    path('contract_delete/<int:pk>/', views.contract_delete, name='contract_delete'),
    path('pdf/', views.render_pdf_view, name='render_pdf_view'),
    
    path('vn_hop_dong_mua_ban_30_ngay/', views.vn_hop_dong_mua_ban_30_ngay, name='vn_hop_dong_mua_ban_30_ngay'),
    path('vn_hop_dong_mua_ban_cod/', views.vn_hop_dong_mua_ban_cod, name='vn_hop_dong_mua_ban_cod'),
    path('vn_hop_dong_mua_ban_nguyen_tac/', views.vn_hop_dong_mua_ban_nguyen_tac, name='vn_hop_dong_mua_ban_nguyen_tac'),
    path('vn_phu_luc_hop_dong/', views.vn_phu_luc_hop_dong, name='vn_phu_luc_hop_dong'),
    path('song_ngu_bien_ban_thanh_ly_hop_dong/', views.song_ngu_bien_ban_thanh_ly_hop_dong, name='song_ngu_bien_ban_thanh_ly_hop_dong'),
    path('song_ngu_phu_luc_chong_pha_gia/', views.song_ngu_phu_luc_chong_pha_gia, name='song_ngu_phu_luc_chong_pha_gia'),
    path('song_ngu_phu_luc_bo_sung_sp/', views.song_ngu_phu_luc_bo_sung_sp, name='song_ngu_phu_luc_bo_sung_sp'),

]

report/urls.py
from argparse import Namespace
from django.urls import path, re_path
from report import views

app_name = 'report'
urlpatterns = [
    path('report_contract/<int:pk>/', views.report_contract, name='report_contract'),
    path('contract_follow_up/<int:pk>/', views.contract_follow_up, name='contract_follow_up'),
    path('report_quotation/<int:pk>/', views.report_quotation, name='report_quotation'),
    path('quotation_follow_up/<int:pk>/', views.quotation_follow_up, name='quotation_follow_up'),
    
    
]

tedisapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers

router = routers.DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sale_agreement.urls')),
    path('', include('sale_management.urls')),
    path('', include('quotation.urls')),
    path('', include('report.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quotation/views.py
from urllib import response
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.template.loader import render_to_string
from datetime import datetime
import pdfkit
from django.core.paginator import Paginator
import quotation
from .models import *
from .forms import *
import os
from django.template.loader import get_template
from xhtml2pdf import pisa
# Create your views here.

# QUOTATION
def quotation_list_status(request, pk):
    # Kiểm tra session xem khách hàng đã đăng nhập chưa?
    if 's_user' not in request.session:
        return redirect('sale_agreement:signin')

    # Create quotation
    form = CreateQuotationForm()
    if request.method == 'POST':
        form = CreateQuotationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/quotation-list-status/0/')
        
    # Đọc danh sách Channel
    list_channel = Channel.objects.order_by('channel_name')
    
    # Đọc danh sách Status
    list_status = Status.objects.order_by('status')
    
    # Đọc danh sách sản phẩm theo status
    if pk == 0:
        quotations = Quotation.objects.order_by('quotation_no')
    else:
        quotations = Quotation.objects.filter(quotation_status=pk).order_by('quotation_no')

    # Phân trang
    page = request.GET.get('page', 1)
    paginator = Paginator(quotations, 15)
    quotation_pager = paginator.page(page)
    
    return render(request, 'quotation/quotation_list.html', {
        'list_channel' : list_channel,
        'list_status' : list_status,
        'quotations' : quotation_pager,
        'customers' : customers,
        'form' : form,
    })


def quotation_delete(request, pk):
    try:
        quotation_info = Quotation.objects.get(id = pk)
    except Quotation.DoesNotExist:
        return redirect('index')
    quotation_info.delete()
    return redirect('/quotation-list-channel/0/')
    
    
def quotation_list_channel(request, pk):
    # Kiểm tra session xem khách hàng đã đăng nhập chưa?
    if 's_user' not in request.session:
        return redirect('sale_agreement:signin')
    
    # Create quotation
    form = CreateQuotationForm()
    if request.method == 'POST':
        form = CreateQuotationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/quotation-list-channel/0/')
    
    # Đọc danh sách Channel
    list_channel = Channel.objects.order_by('channel_name')
    
    # Đọc danh sách Status
    list_status = Status.objects.order_by('status')
    
    # Đọc danh sách sản phẩm theo Channel
    quotations = Quotation.objects.all()
    if pk == 0:
        quotations = Quotation.objects.order_by('quotation_no')
    else:
        # customer_name = Customer.objects.get(customer_name=quotations.customer_id)
        # channel = customer_name.channel
        quotations = Quotation.objects.filter(channel=pk).order_by('quotation_no')

    # Phân trang
    page = request.GET.get('page', 1)
    paginator = Paginator(quotations, 15)
    quotation_pager = paginator.page(page)

    
    return render(request, 'quotation/quotation_list.html', {
        'list_channel' : list_channel,
        'list_status' : list_status,
        'quotations' : quotation_pager,
        'customers' : customers,
        'form' : form,
    })
    

def quotation_update(request, pk):
    # Kiểm tra session xem khách hàng đã đăng nhập chưa?
    if 's_user' not in request.session:
        return redirect('sale_agreement:signin')
    
    # Edit quotation
    quotation = Quotation.objects.get(pk=pk)
    form_update_quotation = CreateQuotationForm(instance=quotation)
    if request.method == 'POST':
        form_update_quotation = CreateQuotationForm(request.POST, instance=quotation)
        if form_update_quotation.is_valid():
            form_update_quotation.save()
            return redirect('/quotation-list-channel/0/')
    return render(request, 'quotation/form_update_quotation.html', {
        'quotation' : quotation,
        'form_update_quotation' : form_update_quotation,
    })


def quotation_product_input(request, pk):
    # Quotation
    quotation = Quotation.objects.get(pk=pk)
    customer_name = Customer.objects.get(customer_name=quotation.customer_id)
    channel = customer_name.channel
    
    # Add product to quotation
    add_product_to_quotation_success_aleart = ''
    products = Product.objects.all()
    channels = Channel.objects.all()
    unit_price_vat = 1
    
    if request.POST.get('btn_addproducttoquotation'):
        quotation_name = request.POST.get('quotation_id') # lấy từ <input type="hidden">
        quotation_id = Quotation.objects.only('id').get(id=quotation_name)
        product_id = request.POST.get('product_id')  
        product_name = Product.objects.only('id').get(id=product_id)
        product = Product.objects.get(id=product_id)
        if str(channel) == 'ETC':
            unit_price_vat = product.selling_price_etc_vat
        if str(channel) == 'OTC':
            unit_price_vat = product.selling_price_otc_vat
        add_product_to_quotation_success_aleart = '''
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                Đã đăng ký thông tin thành công.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        '''
        quotation_product_info = Quotation_product(quotation_id=quotation_id, product_id=product_name, unit_price_vat=unit_price_vat,
                                                    )
        quotation_product_info.save()
        return redirect('/quotation-list-channel/0/')
    
    return render(request, 'quotation/form_add_product_to_quotation.html', {
        'add_product_to_quotation_success_aleart' : add_product_to_quotation_success_aleart,
        'channels' : channels,
        'products' : products,
        'quotation' : quotation,
    })
    

def search_quotation(request):
    # Kiểm tra session xem khách hàng đã đăng nhập chưa?
    if 's_user' not in request.session:
        return redirect('sale_agreement:signin')
    
    # Đọc danh sách Channel
    list_channel = Channel.objects.order_by('channel_name')
    
    # Đọc danh sách Status
    list_status = Status.objects.order_by('status')
    
    # Tìm kiếm
    quotations = []
    keyword = ''
    if request.GET.get('quotation_no'):
        keyword = request.GET.get('quotation_no')
        quotations = Quotation.objects.filter(quotation_no__contains=keyword).order_by('quotation_no')
        
        # Phân trang
        page = request.GET.get('page', 1)
        paginator = Paginator(quotations, 15)
        quotation_pager = paginator.page(page)
    

    return render(request, 'quotation/quotation_list.html', {
        'list_channel' : list_channel,
        'list_status' : list_status,
        'quotations' : quotation_pager,
    })

    
def quotation_product_delete(request, pk):
    try:
        quotation_product_info = Quotation_product.objects.get(id = pk)
    except Product.DoesNotExist:
        return redirect('index')
    quotation_product_info.delete()
    return redirect('/quotation-list-channel/0/')
    

def final_quotation(request, pk):
    # Kiểm tra session xem khách hàng đã đăng nhập chưa?
    if 's_user' not in request.session:
        return redirect('sale_agreement:signin')

    # Lấy thông tin QUOTATION và QUOTATION PRODUCT
    quotation = Quotation.objects.get(pk=pk) 
    quotation_products = Quotation_product.objects.filter(quotation_id=pk)
    # for product in quotation_products:
    #     print(product.quantity)
    
    return render(request, 'quotation/quotation.html', {
        'quotation' : quotation,
        'quotation_products' : quotation_products,  
    })




def html_to_pdf_view(request, pk):
    today = datetime.now().strftime('%d-%m-%Y')

    # Lấy thông tin QUOTATION và QUOTATION PRODUCT
    quotation = Quotation.objects.get(pk=pk) 
    quotation_products = Quotation_product.objects.filter(quotation_id=pk)

    html_string = render_to_string('quotation/vn_hop_dong_mua_ban_cod.html', {
        'today': today,
        'quotation': quotation,
        'quotation_products': quotation_products,
    })
   
    # template = get_template('quotation/final_quotation.html')
    # html = template.render({
    #     'today': today,
    #     'quotation': quotation,
    #     'quotation_products': quotation_products,
    # })
    
    options = {
        'page-size': 'Letter',
        'encoding': "UTF-8",
        # 'orientation': 'Landscape'
    }
    
        
    # result = BytesIO()
    
    # pdf = pisa.pisaDocument(BytesIO(html.encode("utf-8")), result) 
    
    config_path = 'C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe'
    config = pdfkit.configuration(wkhtmltopdf=config_path)
    
    filename = 'report_' + datetime.now().strftime('%Y%m%d_%H%M%S') + '.pdf'
    pdfkit.from_string(html_string, os.path.join(os.path.expanduser('~'), 'Documents', filename), configuration=config)
    # pdfkit.from_string(html_string, "E:\\" + filename, configuration=config, options=options)
    # if not pdf.err:
        # return HttpResponse(result.getvalue(), content_type='application/pdf')

    return HttpResponse(html_string)
    


# SALE AND PURCHASE CONTRACT
def contract(request):
    
    return render(request, 'quotation/contract_1.html')

def vn_hop_dong_mua_ban_30_ngay(request):
    
    return render(request, 'quotation/vn_hop_dong_mua_ban_30_ngay.html')

def vn_hop_dong_mua_ban_cod(request):
    
    return render(request, 'quotation/vn_hop_dong_mua_ban_cod.html')

def vn_hop_dong_mua_ban_nguyen_tac(request):
    
    return render(request, 'quotation/vn_hop_dong_mua_ban_nguyen_tac.html')

def vn_phu_luc_hop_dong(request):
    
    return render(request, 'quotation/vn_phu_luc_hop_dong.html')

quotation/templates/quotation/form_quotation_follow_up.html
{% extends 'sale_agreement/_Master.html' %}
{% block title_tab %}Sales app | Quotation Data Input{% endblock %}
{% load static %}
{% load humanize %}

{% block main_content %}
<nav class="navbar navbar-light bg-white border">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold text-dark" href="#" style="color: #434343; margin-left: 20px">Quotation follow up</a>
    </div>
</nav>
<div class="container-fluid bg-white border" style="width: 97%; margin-top: 20px" >
    <br>
    <div><span class="fw-bold text-dark" style="color: #434343; margin-left: 20px; font-size:medium">Customer: {{ quotation.customer_id }}</span></div>
<form method="post">
    {% csrf_token %}
    <div class="container-fluid">
        <div class="row align-items-start">
        <input type="hidden" name="quotation_id" value="{{ quotation.id }}" />
        <div class="col-6">
            <label for="quotation_status" class="col-form-label fw-bold text-dark">Status</label>
            {{ form_follow_up.quotation_status }}
        </div>
        <div class="col-6">
            <label for="status_date" class="col-form-label fw-bold text-dark">Date</label>
            <br>
            {{ form_follow_up.status_date }}
        </div>
        <br>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end" style="margin-bottom: 20px">
        <a class="btn btn-secondary" href="{% url 'quotation:quotation_list_channel' 0 %}" role="button">Close</a>
        <button type="submit" class="btn btn-primary" name="btn_followup" value="Quotation follow up">Add</button>
    </div>
</form>
</div>
</div>

{% endblock %}

quotation/templates/quotation/pdf1.html
<html>
    <head>
        <meta charset="utf-8">
        <title>Pdf test</title>
    </head>
    <body>
        Ông Phan Hoà Bình, cựu chủ tịch TP Vũng Tàu, bị cáo buộc sai phạm tạo điều kiện cho doanh nghiệp lừa hàng trăm người mua đất dự án nhà ở cao cấp Metropolitan.
        {{myvar}}
    </body>
</html>

quotation/templates/quotation/quotation_list.html
{% extends 'sale_agreement/_Master.html' %}
{% block title_tab %}Sales app | Quotation List{% endblock %}
{% load static %}
{% load humanize %}

{% block main_content %}
<div class="container-fluid pt-4 px-4">
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="border:0.5px solid rgb(204, 204, 204);">
        <div class="container-fluid">
            <a class="navbar-brand fw-bold text-dark" href="{% url 'quotation:quotation_list_channel' 0 %}">Quotation</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Channel
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for channel in list_channel %}
                            <li><a class="dropdown-item" href="{% url 'quotation:quotation_list_channel' channel.pk %}">{{ channel }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Status
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for status in list_status %}
                            <li><a class="dropdown-item" href="{% url 'quotation:quotation_list_status' status.pk %}">{{ status }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
                <div class="btn-group" role="group" style="margin-right: 10px;">
                    <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Action
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                        <li><a href="" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#createquotationModal"><i class="bi bi-file-earmark-plus"></i> Create new</a></li>
                    </ul>
                </div>
                <form method="get" action="{% url 'quotation:search_quotation' %}">
                    <div class="search">
                        <input type="text" name="quotation_no" value="{{ quotation_no }}" placeholder="Search quotation number...">
                        <button type="submit"><i class="fa fa-search"></i></button>
                    </div>
                </form>
            </div>
        </div>
    </nav>
    <table class="table bg-light" style="border:0.5px solid rgb(204, 204, 204); margin-top: 10px">
        <thead class="thead-dark">
            <tr>
                <th scope="col" class="table-dark">Number</th>
                <th scope="col" class="table-dark">Quotation Number</th>
                <th scope="col" class="table-dark">Customer</th>
                <th scope="col" class="table-dark">Channel</th>
                <th scope="col" class="table-dark">Date</th>
                <th scope="col" class="table-dark">Status</th>
                <th scope="col" class="table-dark">Remark</th>
                <th scope="col" class="table-dark"></th>
            </tr>
        </thead>
        <tbody>
            {% for q in quotations %}
            <tr>
                <th scope="row">{{ q.id }}</th>
                <td>{{ q.quotation_no }}</td>
                <td class="text-dark">{{ q.customer_id }}</td>
                <td>{{ q.channel }}</td>
                <td>{{ q.quotation_date }}</td>
                <td>{{ q.quotation_status }}</td>
                <td>{{ q.quotation_remark }}</td>
                <td><div class="dropdown">
                    <button class="btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-tools"></i>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                      <li><a class="dropdown-item" href="{% url 'quotation:quotation_product_input' q.pk %}"><i class="bi bi-plus-square"></i> Add product</a></li>
                      <li><a class="dropdown-item" href="{% url 'quotation:final_quotation' q.pk %}"><i class="bi bi-binoculars"></i> View</a></li>
                      <li><a class="dropdown-item" href="{% url 'quotation:html_to_pdf_view' q.pk %}"><i class="bi bi-file-earmark-arrow-down"></i> Print PDF</a></li>
                      <li><a class="dropdown-item" href="{% url 'quotation:quotation_update' q.pk %}"><i class="bi bi-pencil-fill"></i> Edit</a></li>
                      {% comment %} <li><a class="dropdown-item" href="{% url 'quotation:quotation_follow_up' q.pk %}"><i class="bi bi-calendar-check"></i> Quotation follow up</a></li> {% endcomment %}
                      <li><a class="dropdown-item" href="{% url 'quotation:quotation_delete' q.pk %}"><i style = "color: rgb(180, 28, 28);" class="bi bi-trash"></i> Delete</a></li>
                    </ul>
                  </div></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<!-- Pagination Start -->
<div class="col-md-12">
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">

            {% if quotations.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ quotations.previous_page_number }}{% if request.GET.quotation_no %}&quotation_no={{ request.GET.quotation_no }}{% endif %}" tabindex="-1">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
            {% endif %}

            {% if quotations.number > 5 %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">...</a>
                </li>
            {% endif %}

            {% for i in quotations.paginator.page_range %}
                {% if i > quotations.number|add:"-5" %}
                    {% if i < quotations.number|add:"5" %}
                        {% if quotations.number == i %}
                            <li class="page-item active">
                                <a class="page-link" href="?page={{ i }}{% if request.GET.quotation_no %}&quotation_no={{ request.GET.quotation_no }}{% endif %}">{{ i }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ i }}{% if request.GET.quotation_no %}&quotation_no={{ request.GET.quotation_no }}{% endif %}">{{ i }}</a>
                            </li>
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endfor %}

            {% if quotations.number < quotations.paginator.num_pages|add:"-4" %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">...</a>
                </li>
            {% endif %}

            {% if quotations.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ quotations.next_page_number }}{% if request.GET.quotation_no %}&quotation_no={{ request.GET.quotation_no }}{% endif %}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
            {% endif %}

        </ul>
    </nav>
</div>


<!-- Modals -->

<!-- Create Quotation Modal -->
<div class="modal fade" id="createquotationModal" tabindex="-1" aria-labelledby="createquotationModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div id="addQuotation" class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="createquotationModalLabel">Quotation creation</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form method="post">
              {% csrf_token %}
              <div class="mb-3">
                  <label for="quotation_no" class="col-form-label fw-bold text-dark">Quotation Number</label>
                  {{ form.quotation_no }}
              </div>
              <div class="mb-3">
                  <label for="customer_id" class="col-form-label fw-bold text-dark">Customer</label>
                  {{ form.customer_id }}
              </div>
              <div class="mb-3">
                <label for="channel" class="col-form-label fw-bold text-dark">Channel</label>
                {{ form.channel }}
            </div>
              <div class="mb-3">
                  <label for="quotation_date" class="col-form-label fw-bold text-dark">Quotation Date</label>
                  {{ form.quotation_date }}
              </div>
              <div class="mb-3">
                  <label for="quotation_remark" class="col-form-label fw-bold text-dark">Quotation Remark</label>
                  {{ form.quotation_remark }}
              </div>
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-primary" name="btnquotationinput" value="Quotation input" style="background-color: #9b1b14;">Create quotation</button>
              </div>
          </form>
      </div>
    </div>
  </div>


{% endblock %}