report/urls.py
from argparse import Namespace
from django.urls import path, re_path
from report import views

app_name = 'report'
urlpatterns = [
    path('report_contract/<int:pk>/', views.report_contract, name='report_contract'),
    path('contract_follow_up/<int:pk>/', views.contract_follow_up, name='contract_follow_up'),
    path('report_quotation/<int:pk>/', views.report_quotation, name='report_quotation'),
    path('quotation_follow_up/<int:pk>/', views.quotation_follow_up, name='quotation_follow_up'),
    
    
]

tedisapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers

router = routers.DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sale_agreement.urls')),
    path('', include('sale_management.urls')),
    path('', include('quotation.urls')),
    path('', include('report.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

report/models.py
from django.db import models

# Create your models here.

report/forms.py
from dataclasses import fields
from django import forms
from django.forms import ModelForm, TextInput
from django.forms.models import inlineformset_factory
from quotation.models import *
from .models import *
from django.contrib.admin.widgets import AdminSplitDateTime

statuses = Status.objects.only('id')

class ContractFollowupForm(forms.ModelForm):
    contract_status = forms.ModelChoiceField(required=False, queryset=statuses ,widget=forms.Select(attrs={
        "class": "form-control bg-white text-dark",
    }))
    status_date = forms.DateField(required=False, widget=forms.SelectDateWidget(attrs={
         "placeholder": "Date",
    }))
    class Meta:
        model = Contract
        fields = ['contract_status','status_date']
        

class QuotationFollowupForm(forms.ModelForm):
    quotation_status = forms.ModelChoiceField(required=False, queryset=statuses ,widget=forms.Select(attrs={
        "class": "form-control bg-white", "placeholder": "Customer name",
    }))
    status_date = forms.DateField(required=False, widget=forms.SelectDateWidget(attrs={
         "placeholder": "Quotation date",
    }))
    class Meta:
        model = Quotation
        fields = ['quotation_status','status_date']
        

        

report/views.py
from django.shortcuts import render,redirect
from datetime import datetime
from django.core.paginator import Paginator
from sale_management.models import *
from quotation.models import *
from report.forms import *

# Create your views here.
def report_contract(request, pk):
    # Kiểm tra session xem khách hàng đã đăng nhập chưa?
    if 's_user' not in request.session:
        return redirect('sale_agreement:signin')
    
    # Đọc danh sách Channel
    list_channel = Channel.objects.order_by('channel_name')
    
    # Đọc danh sách Status
    list_status = Status.objects.order_by('status')
    
    # Đọc danh sách all contract theo channel
    if pk == 0:
        contracts = Contract.objects.filter(contract_status=None).order_by('contract_no')
    else:
        contracts = Contract.objects.filter(channel=pk).order_by('contract_no')
        # print(contracts.contract_status)

    # Phân trang all contract
    page = request.GET.get('page', 1)
    paginator = Paginator(contracts, 15)
    contract_pager = paginator.page(page)
            
    # Đọc danh sách "đã chuyển khách hàng" contract
    contracts_da_chuyen_khach_hang = Contract.objects.filter(contract_status=1).order_by('contract_no')

    # Phân trang "đã chuyển khách hàng" contract
    page = request.GET.get('page', 1)
    paginator = Paginator(contracts_da_chuyen_khach_hang, 15)
    contracts_da_chuyen_khach_hang_pager = paginator.page(page)
    
    # Đọc danh sách "đã ký" contract
    contracts_da_ky = Contract.objects.filter(contract_status=2).order_by('contract_no')

    # Phân trang "đã ký" contract
    page = request.GET.get('page', 1)
    paginator = Paginator(contracts_da_ky, 15)
    contracts_da_ky_pager = paginator.page(page)
    
    # Đọc danh sách "hủy" contract
    contracts_huy = Contract.objects.filter(contract_status=3).order_by('contract_no')

    # Phân trang "hủy" contract
    page = request.GET.get('page', 1)
    paginator = Paginator(contracts_huy, 15)
    contracts_huy_pager = paginator.page(page)
    
    return render(request, 'report/report_contract.html', {
        'list_channel' : list_channel,
        'list_status' : list_status,
        'contracts' : contract_pager,
        'contracts_da_chuyen_khach_hang' : contracts_da_chuyen_khach_hang_pager,
        'contracts_da_ky' : contracts_da_ky_pager,
        'contracts_huy' : contracts_huy_pager,
    })

def contract_follow_up(request, pk):
    # Contract
    contract = Contract.objects.get(pk=pk)
    
    # Contract follow up
    form_follow_up = ContractFollowupForm(instance=contract)
    if request.method == 'POST':
        form_follow_up = ContractFollowupForm(request.POST, instance=contract)
        if form_follow_up.is_valid():
            form_follow_up.save()
            return redirect('/report_contract/0/')
    
    return render(request, 'report/form_contract_follow_up.html', {
        'contract' : contract,
        'form_follow_up' : form_follow_up,
    })

def report_quotation(request, pk):
    # Kiểm tra session xem khách hàng đã đăng nhập chưa?
    if 's_user' not in request.session:
        return redirect('sale_agreement:signin')
    
    # Đọc danh sách Channel
    list_channel = Channel.objects.order_by('channel_name')
    
    # Đọc danh sách Status
    list_status = Status.objects.order_by('status')
    
    # Đọc danh sách all quotation theo channel
    if pk == 0:
        quotations = Quotation.objects.filter(quotation_status=None).order_by('quotation_no')
    else:
        quotations = Quotation.objects.filter(channel=pk).order_by('quotation_no')

    # Phân trang all quotation
    page = request.GET.get('page', 1)
    paginator = Paginator(quotations, 15)
    quotation_pager = paginator.page(page)
            
    # Đọc danh sách "đã chuyển khách hàng" quotation
    quotations_da_chuyen_khach_hang = Quotation.objects.filter(quotation_status=1).order_by('quotation_no')

    # Phân trang "đã chuyển khách hàng" quotation
    page = request.GET.get('page', 1)
    paginator = Paginator(quotations_da_chuyen_khach_hang, 15)
    quotations_da_chuyen_khach_hang_pager = paginator.page(page)
    
    # Đọc danh sách "đã ký" quotation
    quotations_da_ky = Quotation.objects.filter(quotation_status=2).order_by('quotation_no')

    # Phân trang "đã ký" quotation
    page = request.GET.get('page', 1)
    paginator = Paginator(quotations_da_ky, 15)
    quotations_da_ky_pager = paginator.page(page)
    
    # Đọc danh sách "hủy" quotation
    quotations_huy = Quotation.objects.filter(quotation_status=3).order_by('quotation_no')

    # Phân trang "hủy" quotation
    page = request.GET.get('page', 1)
    paginator = Paginator(quotations_huy, 15)
    quotations_huy_pager = paginator.page(page)
    
    return render(request, 'report/report_quotation.html', {
        'list_channel' : list_channel,
        'list_status' : list_status,
        'quotations' : quotation_pager,
        'quotations_da_chuyen_khach_hang' : quotations_da_chuyen_khach_hang_pager,
        'quotations_da_ky' : quotations_da_ky_pager,
        'quotations_huy' : quotations_huy_pager,
    })

def quotation_follow_up(request, pk):
    # Quotation
    quotation = Quotation.objects.get(pk=pk)
    
    # Edit customer
    form_follow_up = QuotationFollowupForm(instance=quotation)
    if request.method == 'POST':
        form_follow_up = QuotationFollowupForm(request.POST, instance=quotation)
        if form_follow_up.is_valid():
            form_follow_up.save()
            return redirect('/report_quotation/0/')
    
    return render(request, 'report/form_quotation_follow_up.html', {
        'quotation' : quotation,
        'form_follow_up' : form_follow_up,
    })

report/templates/report/form_contract_follow_up.html
{% extends 'sale_agreement/_Master.html' %}
{% block title_tab %}Sales app | Quotation Data Input{% endblock %}
{% load static %}
{% load humanize %}

{% block main_content %}
<nav class="navbar navbar-light bg-white border">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold text-dark" href="#" style="color: #434343; margin-left: 20px">Contract follow up</a>
    </div>
</nav>
<div class="container-fluid bg-white border" style="width: 97%; margin-top: 20px" >
    <br>
    <div><span class="fw-bold text-dark" style="color: #434343; margin-left: 20px; font-size:medium">Customer: {{ contract.customer_id }}</span></div>
<form method="post">
    {% csrf_token %}
    <div class="container-fluid">
        <div class="row align-items-start">
        <input type="hidden" name="contract_no" value="{{ contract.id }}" />
        <div class="col-6">
            <label for="contract_status" class="col-form-label fw-bold text-dark">Status</label>
            {{ form_follow_up.contract_status }}
        </div>
        <div class="col-6">
            <label for="status_date" class="col-form-label fw-bold text-dark">Date</label>
            <br>
            {{ form_follow_up.status_date }}
        </div>
        <br>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end" style="margin-bottom: 20px">
        <a class="btn btn-secondary" href="{% url 'report:report_contract' 0 %}" role="button">Close</a>
        <button type="submit" class="btn btn-primary" name="btn_followup" value="Quotation follow up">Submit</button>
    </div>
</form>
</div>
</div>

{% endblock %}

report/templates/report/form_quotation_follow_up.html
{% extends 'sale_agreement/_Master.html' %}
{% block title_tab %}Sales app | Quotation Follow Up{% endblock %}
{% load static %}
{% load humanize %}

{% block main_content %}
<nav class="navbar navbar-light bg-white border">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold text-dark" href="#" style="color: #434343; margin-left: 20px">Quotation follow up</a>
    </div>
</nav>
<div class="container-fluid bg-white border" style="width: 97%; margin-top: 20px" >
    <br>
    <div><span class="fw-bold text-dark" style="color: #434343; margin-left: 20px; font-size:medium">Customer: {{ quotation.customer_id }}</span></div>
<form method="post">
    {% csrf_token %}
    <div class="container-fluid">
        <div class="row align-items-start">
        <input type="hidden" name="quotation_id" value="{{ quotation.id }}" />
        <div class="col-6">
            <label for="quotation_status" class="col-form-label fw-bold text-dark">Status</label>
            {{ form_follow_up.quotation_status }}
        </div>
        <div class="col-6">
            <label for="status_date" class="col-form-label fw-bold text-dark">Date</label>
            <br>
            {{ form_follow_up.status_date }}
        </div>
        <br>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end" style="margin-bottom: 20px">
        <a class="btn btn-secondary" href="{% url 'report:report_quotation' 0 %}" role="button">Close</a>
        <button type="submit" class="btn btn-primary" name="btn_followup" value="Quotation follow up">Submit</button>
    </div>
</form>
</div>
</div>

{% endblock %}