quotation/urls.py
from argparse import Namespace
from django.urls import path, re_path
from quotation import views

app_name = 'quotation'
urlpatterns = [
    path('quotation-list-status/<int:pk>/', views.quotation_list_status, name='quotation_list_status'),
    path('quotation-list-channel/<int:pk>/', views.quotation_list_channel, name='quotation_list_channel'),
    path('search_quotation/', views.search_quotation, name='search_quotation'),
    path('quotation_update/<int:pk>/', views.quotation_update, name='quotation_update'),
    path('quotation_delete/<int:pk>/', views.quotation_delete, name='quotation_delete'),
    path('add_product_to_quotation/<int:pk>/', views.quotation_product_input, name='quotation_product_input'),
    path('quotation_product_delete/<int:pk>/', views.quotation_product_delete, name='quotation_product_delete'),
    path('quotation/<int:pk>/', views.final_quotation, name='final_quotation'),
    path('quotation_pdf/<int:pk>/', views.html_to_pdf_view, name='html_to_pdf_view'),
    path('contract/', views.contract, name='contract'),
    path('contract_view/<int:pk>/', views.contract_view, name='contract_view'),
    path('contract-list-status/<int:pk>/', views.contract_list_status, name='contract_list_status'),
    path('contract-list-channel/<int:pk>/', views.contract_list_channel, name='contract_list_channel'),
    path('search_contract/', views.search_contract, name='search_contract'),
    path('contract_update/<int:pk>/', views.contract_update, name='contract_update'),
    path('contract_delete/<int:pk>/', views.contract_delete, name='contract_delete'),
    path('pdf/', views.render_pdf_view, name='render_pdf_view'),
    
    path('vn_hop_dong_mua_ban_30_ngay/', views.vn_hop_dong_mua_ban_30_ngay, name='vn_hop_dong_mua_ban_30_ngay'),
    path('vn_hop_dong_mua_ban_cod/', views.vn_hop_dong_mua_ban_cod, name='vn_hop_dong_mua_ban_cod'),
    path('vn_hop_dong_mua_ban_nguyen_tac/', views.vn_hop_dong_mua_ban_nguyen_tac, name='vn_hop_dong_mua_ban_nguyen_tac'),
    path('vn_phu_luc_hop_dong/', views.vn_phu_luc_hop_dong, name='vn_phu_luc_hop_dong'),
    path('song_ngu_bien_ban_thanh_ly_hop_dong/', views.song_ngu_bien_ban_thanh_ly_hop_dong, name='song_ngu_bien_ban_thanh_ly_hop_dong'),
    path('song_ngu_phu_luc_chong_pha_gia/', views.song_ngu_phu_luc_chong_pha_gia, name='song_ngu_phu_luc_chong_pha_gia'),
    path('song_ngu_phu_luc_bo_sung_sp/', views.song_ngu_phu_luc_bo_sung_sp, name='song_ngu_phu_luc_bo_sung_sp'),

]

report/urls.py
from argparse import Namespace
from django.urls import path, re_path
from report import views

app_name = 'report'
urlpatterns = [
    path('report_contract/<int:pk>/', views.report_contract, name='report_contract'),
    path('contract_follow_up/<int:pk>/', views.contract_follow_up, name='contract_follow_up'),
    path('report_quotation/<int:pk>/', views.report_quotation, name='report_quotation'),
    path('quotation_follow_up/<int:pk>/', views.quotation_follow_up, name='quotation_follow_up'),
    
    
]

sale_agreement/urls.py
from django.urls import path, include
from sale_agreement import views

app_name = 'sale_agreement'
urlpatterns = [
    path('', views.signin, name='signin'),
    path('signup/', views.signup_changepassword, name='signup_changepassword'),
    path('logout/', views.logout, name='logout'),
    path('index/', views.index, name='index'),
    
]

sale_management/urls.py
from django.urls import path
from sale_management import views

app_name = 'sale_management'
urlpatterns = [
    path('product_update/<int:pk>/', views.product_update, name='product_update'),
    path('product_delete/<int:pk>/', views.product_delete, name='product_delete'),
    path('customer_update/<int:pk>/', views.customer_update, name='customer_update'),
    path('customer_delete/<int:pk>/', views.customer_delete, name='customer_delete'),
    path('customer_detail/<int:pk>/', views.customer_detail, name='customer_detail'),
    path('product1/<int:pk>/', views.product1, name='product1'),
    path('product2/<int:pk>/', views.product2, name='product2'),
    path('product_detail/<int:pk>/', views.product_detail, name='product_detail'),
    path('search_product/', views.search_product, name='search_product'),
    path('customer_channel_filter/<int:pk>/', views.customer_channel_filter, name='customer_channel_filter'),
    path('customer_type_filter/<int:pk>/', views.customer_type_filter, name='customer_type_filter'),
    path('customer_salearea_filter/<int:pk>/', views.customer_salearea_filter, name='customer_salearea_filter'),
    path('customer_province_filter/<int:pk>/', views.customer_province_filter, name='customer_province_filter'),
    path('search_customer/', views.search_customer, name='search_customer'),

]

tedisapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.conf.urls.static import static
from django.conf import settings

from rest_framework import routers

router = routers.DefaultRouter()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sale_agreement.urls')),
    path('', include('sale_management.urls')),
    path('', include('quotation.urls')),
    path('', include('report.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sale_agreement/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.
class User(models.Model):
    user_id = models.IntegerField(blank=False)
    user_name = models.CharField(max_length=20, blank=False)
    user_password = models.CharField(max_length=100, blank=False)
    user_full_name = models.CharField(max_length=300, blank=False)
    user_title = models.CharField(max_length=100, blank=False)
    user_mobile_1 = models.CharField(max_length=20, blank=False)
    user_mobile_2 = models.CharField(max_length=20, blank=False)
    user_email = models.EmailField(max_length=50, blank=False)
    user_active = models.CharField(max_length=10)
    created_by = models.IntegerField(null=True)
    created_at = models.DateTimeField(null=True, default=now)
    updated_by = models.IntegerField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    deleted_by = models.IntegerField(null=True, blank=True)
    deleted_at = models.DateTimeField(null=True, blank=True)
    
    
    def __str__(self):
        return self.user_full_name

sale_agreement/forms.py
from django import forms
from sale_agreement.models import User


class FormDangKy(forms.ModelForm):
    user_id = forms.CharField(label='User ID', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "user_id",
    }))
    user_name = forms.CharField(max_length=20, label='Username', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Username",
    }))
    user_password = forms.CharField(max_length=100, label='Mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control", "placeholder": "Mật khẩu",
    }))
    xac_nhan_password = forms.CharField(max_length=100, label='Xác nhận mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control", "placeholder": "Xác nhận mật khẩu",
    }))
    user_full_name = forms.CharField(max_length=300, label='Full name', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Full name",
    }))
    user_title = forms.CharField(max_length=100, label='Title', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Title",
    }))
    user_mobile_1 = forms.CharField(max_length=20, label='Điện thoại 1', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Điện thoại",
    }))
    user_mobile_2 = forms.CharField(max_length=20, label='Điện thoại 2', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Điện thoại",
    }))
    user_email = forms.EmailField(max_length=50, label='Email', widget=forms.TextInput(attrs={
        "class": "form-control", "placeholder": "Email",
    }))
    created_by = forms.IntegerField(label='Created By', widget=forms.NumberInput(attrs={
        "class": "form-control", "placeholder": "created_by",
    }))

    class Meta:
        model = User
        fields = ['user_id', 'user_name', 'user_password', 'user_full_name', 'user_title', 'user_mobile_1','user_mobile_2','user_email']


class FormDoiMatKhau(forms.ModelForm):
    mat_khau_hien_tai = forms.CharField(label='Mật khẩu hiện tại', widget=forms.PasswordInput(attrs={
        "class": "form-control", "placeholder": "Mật khẩu hiện tại",
    }))
    user_password = forms.CharField(label='Mật khẩu mới', widget=forms.PasswordInput(attrs={
        "class": "form-control", "placeholder": "Mật khẩu mới",
    }))
    xac_nhan_mat_khau = forms.CharField(label='Xác nhận Mật khẩu', widget=forms.PasswordInput(attrs={
        "class": "form-control", "placeholder": "Xác nhận Mật khẩu",
    }))

    class Meta:
        model = User
        fields = ['mat_khau_hien_tai', 'user_password', 'xac_nhan_mat_khau']

sale_agreement/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import PBKDF2PasswordHasher, Argon2PasswordHasher, CryptPasswordHasher, BCryptPasswordHasher
from sale_agreement.models import User
from sale_agreement.forms import FormDangKy, FormDoiMatKhau
from datetime import datetime

# Create your views here.
def index(request):
    # Kiểm tra session xem khách hàng đã đăng nhập chưa?
    if 's_user' not in request.session:
        return redirect('sale_agreement:signin')
    
    user_info = User.objects.all()
    s_user = request.session.get('s_user')
        # user = User.objects.get(id=s_user['id'])
        
    return render(request, 'sale_agreement/index.html' , {
        'user_info' : user_info,
    })

def signin(request):
    # Kiểm tra session xem khách hàng đã đăng nhập chưa?
    if 's_user' in request.session:
        return redirect('sale_agreement:index')

    # ĐĂNG NHẬP
    chuoi_kq_dang_nhap = ''
    if request.POST.get('btnDangNhap'):
        # Gán biến
        user_name = request.POST.get('user_name')
        user_password = request.POST.get('user_password')
        hasher = Argon2PasswordHasher()
        # encoded = hasher.encode(user_password, '12345678')

        # Đọc dữ liệu từ CSDL
        # user = User.objects.filter(user_name=user_name, user_password=encoded)
        user = User.objects.filter(user_name=user_name, user_password=user_password)
        # print(user.count())
        if user.count() > 0:
            # Tạo session
            list_user_values = []
            # usn = user.values()[0][user_name]
            request.session['s_user'] = user.values()[0]['user_name']
            # print(user.values()[0]['user_name', 'user_full_name'])
            return redirect('sale_agreement:index')
        else:
            chuoi_kq_dang_nhap = '''
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    Đăng nhập không thành công. Vui lòng kiểm tra lại.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            '''

    return render(request, 'sale_agreement/signin.html', {
        'chuoi_kq_dang_nhap' : chuoi_kq_dang_nhap,
        
    })


def logout(request):
    if 's_user' in request.session:
        del request.session['s_user']
    return redirect('sale_agreement:signin')


def signup_changepassword(request):
    # ĐĂNG KÝ
    frm_dang_ky = FormDangKy()
    chuoi_kq_dang_ky = ''
    if request.POST.get('btnDangKy'):
        frm_dang_ky = FormDangKy(request.POST, User)
        if frm_dang_ky.is_valid(): #and frm_dang_ky.cleaned_data['user_password'] == frm_dang_ky.cleaned_data['user_password']:
            # hasher = PBKDF2PasswordHasher() # salt: 1 byte
            ngayhienhanh = datetime.now()
            hasher = Argon2PasswordHasher() # salt: 8 bytes # dùng để mã hóa password nhưng hiện tại chưa cần vì không ai vào cắp password
            request.POST.__mutable = True
            post = frm_dang_ky.save(commit=False)
            post.user_id = frm_dang_ky.cleaned_data['user_id']
            post.user_name = frm_dang_ky.cleaned_data['user_name']
            # post.user_password = hasher.encode(frm_dang_ky.cleaned_data['user_password'], '12345678')
            post.user_password = frm_dang_ky.cleaned_data['user_password']
            post.user_full_name = frm_dang_ky.cleaned_data['user_full_name']
            post.user_title = frm_dang_ky.cleaned_data['user_title']
            post.user_mobile_1 = frm_dang_ky.cleaned_data['user_mobile_1']
            post.user_mobile_2 = frm_dang_ky.cleaned_data['user_mobile_2']
            post.user_email = frm_dang_ky.cleaned_data['user_email']
            post.created_by = frm_dang_ky.cleaned_data['created_by']
            post.create_at = ngayhienhanh
            post.save()
            chuoi_kq_dang_ky = '''
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    Đã đăng ký thông tin thành công.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            '''
        
    # Đổi mật khẩu
    form = FormDoiMatKhau()
    if request.POST.get('btnChangePass'):
        form = FormDoiMatKhau(request.POST, User)
        if form.is_valid():
            mat_khau_hien_tai = form.cleaned_data['mat_khau_hien_tai']
            s_user = request.session.get('s_user')
            user = User.objects.get(id=s_user['id'])

            # hasher = Argon2PasswordHasher()
            # encoded = hasher.encode(mat_khau_hien_tai, '12345678')

            # if encoded == user.user_password:
            if form.cleaned_data['user_password'] == form.cleaned_data['xac_nhan_mat_khau']:
                    print('change pass')
    return render(request, 'sale_agreement/signup.html', {
        'frm_dang_ky': frm_dang_ky,
        'chuoi_kq_dang_ky': chuoi_kq_dang_ky,
        'form': form,
    })









def quotation(request):
    
    return render(request, 'sale_agreement/index.html')


def agreement(request):
    
    return render(request, 'sale_agreement/index.html')

def showdata(request):
    
    return render(request, 'sale_agreement/index.html')

sale_agreement/templates/sale_agreement/_Master.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title_tab %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'sale_agreement/img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">


    <!-- Libraries Stylesheet -->
    <link href="{% static 'sale_agreement/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'sale_agreement/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}"
        rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'sale_agreement/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'sale_agreement/css/style.css' %}" rel="stylesheet">



    {% comment %}
    <script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script> {% endcomment %}
</head>

<body>
    {% comment %} <div class="container-fluid position-relative bg-white d-flex p-0"> {% endcomment %}
        {% comment %}
        <!-- Spinner Start -->
        <div id="spinner"
            class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End --> {% endcomment %}


        <!-- Sidebar Start -->
        <div class="sidebar" style="background-color: #434343">
            <nav class="navbar navbar-light" style="background-color: #434343;">
                <a href="{% url 'sale_agreement:index' %}" class="navbar-brand mx-4 mb-3">
                    <img class="bg-white" src="{% static 'sale_agreement/img/logo_tedis.png' %}" style=" width:
                        100px; height: 50px;">
                </a>

                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="{% static 'sale_agreement/img/user_3.jpg' %}" alt=""
                            style="width: 35px; height: 35px;">
                        <div
                            class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1">
                        </div>
                    </div>
                    <div class="ms-3" style="margin-right: 15px;">
                        <h6 class="mb-0 text-white">{{ request.session.s_user }}</h6>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown"><i
                                class='fas fa-align-left text-dark'></i> Directory <span
                                class="sr-only">(current)</span></a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{% url 'sale_management:product1' 0 %}" class="dropdown-item text-white">Product
                                <span class="sr-only">(current)</span></a>
                            <a href="{% url 'sale_management:customer_channel_filter' 0 %}"
                                class="dropdown-item text-white">Customer <span class="sr-only">(current)</span></a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown"><i
                                class='far fa-file-alt text-dark'></i> Agreement <span
                                class="sr-only">(current)</span></a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{% url 'quotation:quotation_list_channel' 0 %}"
                                class="dropdown-item text-white">Quotation <span class="sr-only">(current)</span></a>
                            <a href="{% url 'quotation:contract_list_status' 0 %}" class="dropdown-item text-white">Sale
                                contract <span class="sr-only">(current)</span></a>
                        </div>
                    </div>
                    <div class="nav-item">
                        <a href="{% url 'report:report_contract' 0 %}" class="nav-link text-white"><i
                                class="fas fa-chart-bar text-dark"></i> Report <span
                                class="sr-only">(current)</span></a>
                    </div>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->


        <!-- Content Start -->
        <div class="content bg-white">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand sticky-top px-4 py-0" style="background-color: #434343;">
                <a href="{% url 'sale_agreement:index' %}" class="navbar-brand d-flex d-lg-none me-4">
                    <img class="bg-white" src="{% static 'sale_agreement/img/logo_tedis.png' %}" style=" width:
                        100px; height: 50px;">
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0 text-white" style="background-color: #9b1b14;">
                    <i class="fa fa-bars"></i>
                </a>
                <div class="navbar-nav align-items-center ms-auto">
                    {% if request.session.s_user %}
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle text-white" data-bs-toggle="dropdown">
                            {{ request.session.s_user }}</a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            {% comment %} <a href="#" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a> {% endcomment %}
                            <a href="{% url 'sale_agreement:logout' %}" class="dropdown-item">Log Out</a>
                        </div>
                    </div>

                    {% else %}

                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">chua co session</a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a>
                            <a href="{% url 'sale_agreement:logout' %}" class="dropdown-item">Log Out</a>
                        </div>
                    </div>

                    {% endif %}
                </div>
            </nav>
            <!-- Navbar End -->

            <!--Main content-->
            {% block main_content %}{% endblock %}
            <!--End Main content-->

            <!-- Footer Start -->

            {% comment %} <div class="fixed-bottom">
                <div class="container-fluid pt-4 px-4">
                    <div class="bg-light rounded-top p-4">
                        <div class="row">
                            <div class="col-12 col-sm-6 text-center text-sm-start">
                                &copy; <a href="#">NVAK</a>, All Right Reserved.
                            </div>
                            <!-- <div class="col-12 col-sm-6 text-center text-sm-end"> -->
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            <!-- Designed By <a href="https://htmlcodex.com">HTML Codex</a> -->
                        </div>
                    </div>
                </div>
            </div>
        </div> {% endcomment %}
        <!-- Footer End -->
    </div>
    <!-- Content End -->


    <!-- Back to Top -->
    {% comment %} <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i
            class="bi bi-arrow-up"></i></a> {% endcomment %}
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'sale_agreement/lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'sale_agreement/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'sale_agreement/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'sale_agreement/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'sale_agreement/lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'sale_agreement/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'sale_agreement/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'sale_agreement/js/main.js' %}"></script>
</body>

</html>

sale_agreement/templates/sale_agreement/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Test App</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'sale_agreement/img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'sale_agreement/lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'sale_agreement/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css' %}"
        rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'sale_agreement/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'sale_agreement/css/style.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container-fluid position-relative bg-white d-flex p-0">
        {% comment %}
        <!-- Spinner Start -->
        <div id="spinner"
            class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End --> {% endcomment %}


        <!-- Sign In Start -->
        <div class="container-fluid">
            <div class="row h-100 align-items-center justify-content-center" style="min-height: 100vh;">
                <div class="col-12 col-sm-8 col-md-6 col-lg-5 col-xl-4">
                    <div class="bg-light rounded p-2 p-sm-5 my-4 mx-3">
                        <div class="d-flex align-items-center justify-content-between mb-3">
                            <a class="">
                                <img class="bg-white" src="{% static 'sale_agreement/img/logo_tedis.png' %}" alt=""
                                    style="width: 150px; height: 80px;">
                            </a>
                            <h4>TEST APP SIGN IN</h4>
                        </div>
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-floating mb-3">
                                <input class="form-control" id="floatingInput" name="user_name" placeholder="Username">
                                <label for="floatingInput">Username</label>
                            </div>
                            <div class="form-floating mb-4">
                                <input type="password" class="form-control" id="floatingPassword" name="user_password"
                                    placeholder="Password">
                                <label for="floatingPassword">Password</label>
                            </div>
                            <div class="d-flex align-items-center justify-content-between mb-4">
                            </div>
                            <button type="submit" class="btn btn-dark py-3 w-100 mb-4" name="btnDangNhap"
                                value="Đăng nhập">Sign In</button>
                        </form>
                        {% comment %} <p class="text-center mb-0">Do not have an Account ? <a
                                href="{% url 'sale_agreement:signup_changepassword' %}">Sign up</a></p> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
        <!-- Sign In End -->
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'sale_agreement/lib/chart/chart.min.js' %}"></script>
    <script src="{% static 'sale_agreement/lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'sale_agreement/lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'sale_agreement/lib/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'sale_agreement/lib/tempusdominus/js/moment.min.js' %}"></script>
    <script src="{% static 'sale_agreement/lib/tempusdominus/js/moment-timezone.min.js' %}"></script>
    <script src="{% static 'sale_agreement/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js' %}"></script>


    <!-- Template Javascript -->
    <script src="{% static 'sale_agreement/js/main.js' %}"></script>
</body>

</html>